# Generated by Django 3.2.3 on 2021-06-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_pwd_contact_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='usrname',
        ),
    ]
