# Generated by Django 3.2.3 on 2021-06-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_email_contact_usrname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='usrname',
            new_name='username',
        ),
    ]
