# Generated by Django 3.2.3 on 2021-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_cps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('source', models.CharField(max_length=122)),
                ('destination', models.CharField(max_length=122)),
                ('car', models.CharField(max_length=122)),
                ('contact', models.CharField(max_length=122)),
            ],
            options={
                'db_table': 'ride',
            },
        ),
    ]
