# Generated by Django 3.2.3 on 2021-06-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
