# Generated by Django 3.2.3 on 2021-06-11 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_ride_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
