# Generated by Django 3.2.3 on 2021-06-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ride_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='datetime',
        ),
    ]
