# Generated by Django 3.2.3 on 2021-06-18 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_ride_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
