# Generated by Django 3.2.3 on 2021-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_ride_dttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dttime',
            field=models.DateField(),
        ),
    ]
