# Generated by Django 3.2.3 on 2021-06-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_ride_dttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='dttime',
        ),
    ]
